version: "3.7"

services:
  nginx:
    build:
      context: ../TypeDoqer
      dockerfile: nginx/Dockerfile
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php-fpm
    volumes:
      - ../.:/var/www/${PROJECT_NAME}
  php-fpm:
    build:
      context: ../TypeDoqer
      dockerfile: php-fpm/Dockerfile
      args:
        - INSTALL_SOCKET=${INSTALL_SOCKET}
        - INSTALL_MAIL_PARSE=${INSTALL_MAIL_PARSE}
        - INSTALL_PDO=${INSTALL_PDO}
        - INSTALL_LIB_XML=${INSTALL_LIB_XML}
        - INSTALL_OPEN_SSL=${INSTALL_OPEN_SSL}
        - INSTALL_JSON=${INSTALL_JSON}
        - INSTALL_SOAP=${INSTALL_SOAP}
        - INSTALL_MBSTRING=${INSTALL_MBSTRING}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
        - ../.:/var/www/${PROJECT_NAME}
    depends_on:
      - mysql
      - rabbitmq
  mysql:
    build:
      context: ../TypeDoqer
      dockerfile: mysql/Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ../data/mysql:/var/lib/mysql
  rabbitmq:
    build:
      context: ../TypeDoqer
      dockerfile: rabbitmq/Dockerfile
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
    environment:
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq

